sudo: false
language: ruby
rvm:
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - 2.4.1
services:
  - rabbitmq
  - redis
env:
  - RACK_ENV=development
script:
  - gem install bundler --version 1.15.1
  - bundle exec rake
